name: CICD Pipeline
run-name: CICD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master
      
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: temp
        run: |
          rm -r .git
          rm -r .github
          ls
 
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0
      
      - name: databricks-import-directory
        uses: microsoft/databricks-import-notebook@v1.0.0
        with:
          # Databricks host
          databricks-host: https://adb-415647524744627.7.azuredatabricks.net/
          # Databricks token
          databricks-token: ${{ secrets.AZURE_DATABRICKS_ACCESS_TOKEN }}
          # LOCAL_NOTEBOOKS_PATH
          local-path: /home/runner/work/adb-cicd/adb-cicd
          # REMOTE_NOTEBOOK_PATH
          remote-path: /Workspace/Users/lknovember2022@gmail.com
